services:
  backend:
    build:
      context: ./todo_app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo_app_backend:/app

  frontend:
    build:
      context: ./todo-app-front
    ports:
      - "5173:5173"
    volumes:
      - ./todo-app-front:/app
    environment:
      VITE_BACKEND_URL: "http://localhost:8000"